# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            DevNotes
tagline:          'Bitácora tecnológica'
description:      'Bitácora tecnológica. Rincón donde apunto las cosas que pruebo y aprendo.'
url:              http://jamvius.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jamvius
  username:       jamvius

sass:
#  style: :compressed

linkedin:
  username: jamartinezvillar

twitter:
  username: jamvius

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'

gems: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-archives