# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            DevNotes
tagline:          'Bitácora tecnológica'
description:      'Bitácora tecnológica. Rincón donde apunto las cosas que pruebo y aprendo.'
url:              http://jamvius.github.io
baseurl:          /

author:
  name:           'Jamvius'
  url:            https://twitter.com/jamvius

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jamvius

sass:
#  style: :compressed

twitter_username: jamvius
github_username:  jamvius
linkedin_username: jamartinezvillar

jekyll-archives:
  enabled: all
  layout: 'archive'
  layouts:
    year: 'year-archive'
    month: 'month-archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'

gems: ['jekyll-paginate','jekyll-sitemap','jekyll-seo-tag','jekyll-archives']