# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            DevNotes
tagline:          'Apuntas y notas varias'
description:      'by <a href="https://twitter.com/jamvius" target="_blank">@jamvius</a>'
url:              http://jamvius.github.io
baseurl:          /

author:
  name:           'Jamvius'
  url:            https://twitter.com/jamvius

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jamvius

sass:
  style: :compressed
